
name: Deploy Resume

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - uses: whoan/docker-build-with-cache-action@v5
      with:
        username: jordancrane
        password: "${{ secrets.DOCKER_HUB_PASSWORD }}"
        image_name: resume-make
        dockerfile: .docker/resume.dockerfile

    - name: Build
      run: ./build.sh

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
