
name: Deploy Resume

on:
  push:
    branches: [ gh-actions ]

jobs:
  build:
    runs-on: ubuntu-latest

    container: 
      image: jordancrane/resume-make
      volumes:
        - ${{ env.GITHUB_WORKSPACE }}:/home/app/resume

    steps:
      - name: Build
        run: make

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - run: mkdir public && cd output && cp resume.html ../public/index.html cp resume.pdf resume.rtf resume.docx ../public/

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
